export type Personagem = {
  id: number;
  nome: string;
  dica_dificil: string;
  dica_media: string;
  dica_facil: string;
  referencia: string;
  curiosidade: string;
};

export const personagens: Personagem[] = [
  { id: 1, nome: "ADÃO", dica_dificil: "Recebi a tarefa de dar nome aos animais.", dica_media: "Fui formado do pó do solo.", dica_facil: "Fui o primeiro homem.", referencia: "Gênesis 2:7", curiosidade: "Vivi 930 anos." },
  { id: 2, nome: "EVA", dica_dificil: "Fui chamada de mãe de todos os viventes.", dica_media: "Fui formada de uma costela.", dica_facil: "Fui a primeira mulher.", referencia: "Gênesis 3:20", curiosidade: "Meu nome está ligado à ideia de vida." },
  { id: 3, nome: "ABEL", dica_dificil: "Minha oferta foi aceita por Jeová.", dica_media: "Trabalhava como pastor de ovelhas.", dica_facil: "Fui morto por meu irmão.", referencia: "Gênesis 4:4", curiosidade: "Jesus me citou como justo." },
  { id: 4, nome: "NOÉ", dica_dificil: "Anunciei aviso divino antes do Dilúvio.", dica_media: "Construí uma arca enorme.", dica_facil: "Sobrevivi ao Dilúvio com minha família.", referencia: "Gênesis 6:14", curiosidade: "Foi dito que eu andava com o verdadeiro Deus." },
  { id: 5, nome: "ABRAÃO", dica_dificil: "Vim de Ur dos caldeus.", dica_media: "Fui chamado amigo de Jeová.", dica_facil: "Quase ofereci meu filho Isaque.", referencia: "Gênesis 22:2", curiosidade: "Meu nome antes era Abrão." },
  { id: 6, nome: "SARA", dica_dificil: "Ri ao ouvir que teria um filho na velhice.", dica_media: "Meu nome antes era Sarai.", dica_facil: "Sou esposa de Abraão e mãe de Isaque.", referencia: "Gênesis 18:12", curiosidade: "Morreu em Quiriate-Arba." },
  { id: 7, nome: "ISAQUE", dica_dificil: "Cavei poços em Gerar.", dica_media: "Recebi Rebeca como esposa.", dica_facil: "Sou filho de Abraão e Sara.", referencia: "Gênesis 26:18", curiosidade: "Foi em mim que a linhagem da promessa continuou." },
  { id: 8, nome: "REBECA", dica_dificil: "Dei água a camelos de um servo viajante.", dica_media: "Era parenta de Abraão.", dica_facil: "Sou esposa de Isaque.", referencia: "Gênesis 24:19", curiosidade: "Tive dois filhos gêmeos." },
  { id: 9, nome: "JACÓ", dica_dificil: "Vi uma escada em sonho.", dica_media: "Meu nome mudou para Israel.", dica_facil: "Sou pai das 12 tribos.", referencia: "Gênesis 32:28", curiosidade: "Trabalhou 14 anos para casar com Raquel." },
  { id: 10, nome: "JOSÉ", dica_dificil: "Interpretei sonhos de Faraó.", dica_media: "Fui vendido como escravo por meus irmãos.", dica_facil: "Tornei-me governador do Egito.", referencia: "Gênesis 41:41", curiosidade: "Perdoou seus irmãos após grande prova." },
  { id: 11, nome: "MOISÉS", dica_dificil: "Fui educado na sabedoria dos egípcios.", dica_media: "Minha vara se tornou serpente diante de Faraó.", dica_facil: "Liderei Israel para fora do Egito.", referencia: "Êxodo 14:21", curiosidade: "Foi chamado de o homem mais manso da terra." },
  { id: 12, nome: "ARÃO", dica_dificil: "Meu cajado floresceu para confirmar uma escolha.", dica_media: "Atuei como porta-voz de Moisés.", dica_facil: "Fui o primeiro sumo sacerdote de Israel.", referencia: "Números 17:8", curiosidade: "Pertencia à tribo de Levi." },
  { id: 13, nome: "MIRIÃ", dica_dificil: "Conduzi mulheres com pandeiros após grande livramento.", dica_media: "Fui chamada de profetisa.", dica_facil: "Sou irmã de Moisés.", referencia: "Êxodo 15:20", curiosidade: "Vigiou Moisés quando bebê." },
  { id: 14, nome: "JOSUÉ", dica_dificil: "Fui um dos espias fiéis enviados a Canaã.", dica_media: "Assumi a liderança depois de Moisés.", dica_facil: "Liderei a queda de Jericó.", referencia: "Josué 6:20", curiosidade: "Meu nome antes era Oseias." },
  { id: 15, nome: "CALEBE", dica_dificil: "Aos 85 anos, pedi a região montanhosa.", dica_media: "Fui espia fiel com Josué.", dica_facil: "Mostrei coragem quando outros tiveram medo.", referencia: "Josué 14:12", curiosidade: "Jeová disse que eu tinha espírito diferente." },
  { id: 16, nome: "DÉBORA", dica_dificil: "Julgava Israel debaixo de uma palmeira.", dica_media: "Cantei vitória com Baraque.", dica_facil: "Fui profetisa e juíza.", referencia: "Juízes 4:4", curiosidade: "É uma das mulheres mais destacadas do período dos juízes." },
  { id: 17, nome: "GIDEÃO", dica_dificil: "Derrotei inimigos com apenas 300 homens.", dica_media: "Pedi sinais envolvendo lã.", dica_facil: "Fui usado por Jeová contra os midianitas.", referencia: "Juízes 7:7", curiosidade: "Também foi chamado Jerubaal." },
  { id: 18, nome: "SANSÃO", dica_dificil: "Matei mil homens com uma queixada.", dica_media: "Perdi força ao perder meu voto.", dica_facil: "Derrubei o templo dos filisteus.", referencia: "Juízes 16:30", curiosidade: "Foi nazireu desde o ventre." },
  { id: 19, nome: "RUTE", dica_dificil: "Apanhei espigas no campo de Boaz.", dica_media: "Disse que o povo de Noemi seria meu povo.", dica_facil: "Moabita fiel que entrou na linhagem do Messias.", referencia: "Rute 1:16", curiosidade: "Foi bisavó do rei Davi." },
  { id: 20, nome: "SAMUEL", dica_dificil: "Ouvi meu nome enquanto era menino no tabernáculo.", dica_media: "Ungi Saul e depois Davi.", dica_facil: "Fui profeta e juiz de Israel.", referencia: "1 Samuel 3:10", curiosidade: "Nenhuma de suas palavras caiu por terra." },
  { id: 21, nome: "SAUL", dica_dificil: "Busquei uma médium em En-Dor.", dica_media: "Fui ungido quando procurava jumentas perdidas.", dica_facil: "Fui o primeiro rei de Israel.", referencia: "1 Samuel 10:1", curiosidade: "Começou humilde, mas se tornou desobediente." },
  { id: 22, nome: "DAVI", dica_dificil: "Recusei matar Saul por ser o ungido de Jeová.", dica_media: "Toquei harpa para o rei.", dica_facil: "Derrotei Golias com funda.", referencia: "1 Samuel 17:49", curiosidade: "Escreveu muitos salmos." },
  { id: 23, nome: "SALOMÃO", dica_dificil: "Julguei duas mulheres sobre um bebê.", dica_media: "Pedi sabedoria em vez de riquezas.", dica_facil: "Construí o templo de Jerusalém.", referencia: "1 Reis 3:9", curiosidade: "Sua fama atraiu a rainha de Sabá." },
  { id: 24, nome: "ELIAS", dica_dificil: "Fui alimentado por corvos em tempo de seca.", dica_media: "Desafiei os profetas de Baal no Carmelo.", dica_facil: "Orei e fogo desceu do céu.", referencia: "1 Reis 18:38", curiosidade: "Foi levado em vendaval." },
  { id: 25, nome: "ELISEU", dica_dificil: "Um machado flutuou em meu ministério.", dica_media: "Recebi porção dobrada do espírito de Elias.", dica_facil: "Curei Naamã da lepra.", referencia: "2 Reis 5:14", curiosidade: "Realizou muitos milagres." },
  { id: 26, nome: "ISAÍAS", dica_dificil: "Teve visão da glória de Jeová no templo.", dica_media: "Profetizei sobre Emanuel.", dica_facil: "Anunciei muitas profecias messiânicas.", referencia: "Isaías 7:14", curiosidade: "Seu livro é amplamente citado." },
  { id: 27, nome: "JEREMIAS", dica_dificil: "Fui lançado numa cisterna com lama.", dica_media: "Era conhecido como profeta das lágrimas.", dica_facil: "Anunciei a queda de Jerusalém.", referencia: "Jeremias 38:6", curiosidade: "Escreveu Lamentações." },
  { id: 28, nome: "EZEQUIEL", dica_dificil: "Vi rodas impressionantes em visão.", dica_media: "Profetizei no exílio em Babilônia.", dica_facil: "Falei sobre o vale de ossos secos.", referencia: "Ezequiel 37:1", curiosidade: "Atuou como sentinela para Israel." },
  { id: 29, nome: "DANIEL", dica_dificil: "Recusei alimentos do rei por consciência.", dica_media: "Interpretei escrita na parede.", dica_facil: "Fui lançado na cova dos leões.", referencia: "Daniel 6:22", curiosidade: "Teve visões sobre reinos mundiais." },
  { id: 30, nome: "ESTER", dica_dificil: "Preparei banquetes antes de revelar um plano perverso.", dica_media: "Arrisquei a vida ao entrar sem convite.", dica_facil: "Rainha que salvou os judeus.", referencia: "Ester 4:14", curiosidade: "Seu nome hebraico era Hadassa." },
  { id: 31, nome: "MARDOQUEU", dica_dificil: "Descobri conspiração contra o rei.", dica_media: "Recusei me curvar a Hamã.", dica_facil: "Parente e orientador de Ester.", referencia: "Ester 6:2", curiosidade: "Foi honrado publicamente em Susã." },
  { id: 32, nome: "ESDRAS", dica_dificil: "Preparei o coração para ensinar a Lei.", dica_media: "Era copista habilidoso.", dica_facil: "Liderou retorno e reforma espiritual.", referencia: "Esdras 7:10", curiosidade: "Trabalhou para fortalecer a adoração pura." },
  { id: 33, nome: "NEEMIAS", dica_dificil: "Trabalhamos com ferramenta e arma ao mesmo tempo.", dica_media: "Era copeiro do rei antes da missão.", dica_facil: "Reconstruí os muros de Jerusalém.", referencia: "Neemias 4:17", curiosidade: "Concluiu os muros em tempo notável." },
  { id: 34, nome: "JÓ", dica_dificil: "Perdi filhos, bens e saúde em provações.", dica_media: "Manteve integridade diante de acusações.", dica_facil: "Exemplo de perseverança.", referencia: "Jó 1:22", curiosidade: "Recebeu bênçãos em dobro ao final." },
  { id: 35, nome: "JONAS", dica_dificil: "Fugi para Társis no início da missão.", dica_media: "Passei três dias dentro de um grande peixe.", dica_facil: "Preguei arrependimento em Nínive.", referencia: "Jonas 3:3", curiosidade: "Aprendeu lição com uma planta." },
  { id: 36, nome: "JOÃO BATISTA", dica_dificil: "Vivia no deserto com alimentação simples.", dica_media: "Preparou o caminho para o Messias.", dica_facil: "Batizou Jesus.", referencia: "Mateus 3:13", curiosidade: "Seu pai era Zacarias." },
  { id: 37, nome: "MARIA", dica_dificil: "Guardava no coração os acontecimentos.", dica_media: "Recebeu anúncio de um anjo.", dica_facil: "Mãe de Jesus.", referencia: "Lucas 1:30-31", curiosidade: "Também esteve com discípulos em Pentecostes." },
  { id: 38, nome: "JOSÉ", dica_dificil: "Recebeu orientação em sonhos para proteger a família.", dica_media: "Mudou-se para o Egito por segurança.", dica_facil: "Pai adotivo de Jesus.", referencia: "Mateus 2:13", curiosidade: "Era descendente de Davi." },
  { id: 39, nome: "PEDRO", dica_dificil: "Teve visão que abriu caminho para gentios.", dica_media: "Negou Jesus três vezes.", dica_facil: "Apóstolo pescador que falou em Pentecostes.", referencia: "Atos 2:14", curiosidade: "Também era chamado Cefas." },
  { id: 40, nome: "ANDRÉ", dica_dificil: "Seguiu Jesus após ouvir João Batista.", dica_media: "Apresentou seu irmão a Jesus.", dica_facil: "Irmão de Pedro e apóstolo.", referencia: "João 1:40-42", curiosidade: "Era de Betsaida." },
  { id: 41, nome: "TIAGO", dica_dificil: "Era filho de Zebedeu.", dica_media: "Esteve na transfiguração.", dica_facil: "Apóstolo e irmão de João.", referencia: "Mateus 17:1", curiosidade: "Morreu por ordem de Herodes Agripa I." },
  { id: 42, nome: "JOÃO", dica_dificil: "Recebeu revelações em Patmos.", dica_media: "Escreveu evangelho com foco no amor.", dica_facil: "Escreveu Apocalipse.", referencia: "Apocalipse 1:9", curiosidade: "Foi conhecido como discípulo amado." },
  { id: 43, nome: "FILIPE", dica_dificil: "Perguntou a Jesus sobre ver o Pai.", dica_media: "Chamou Natanael para conhecer o Messias.", dica_facil: "Apóstolo citado na multiplicação dos pães.", referencia: "João 14:8", curiosidade: "Também era de Betsaida." },
  { id: 44, nome: "TOMÉ", dica_dificil: "Também era chamado Dídimo.", dica_media: "Quis evidências da ressurreição.", dica_facil: "Apóstolo conhecido por ter duvidado.", referencia: "João 20:25", curiosidade: "Depois fez forte declaração de fé." },
  { id: 45, nome: "MATEUS", dica_dificil: "Trabalhava coletando impostos.", dica_media: "Também era chamado Levi.", dica_facil: "Apóstolo que escreveu um evangelho.", referencia: "Mateus 9:9", curiosidade: "Seu evangelho destaca muitas profecias cumpridas." },
  { id: 46, nome: "PAULO", dica_dificil: "Defendeu-se diante de governadores e reis.", dica_media: "Ficou temporariamente cego em Damasco.", dica_facil: "Missionário que escreveu muitas cartas.", referencia: "Atos 9:3-6", curiosidade: "Antes era chamado Saulo." },
  { id: 47, nome: "BARNABÉ", dica_dificil: "Seu nome significa Filho de Encorajamento.", dica_media: "Ajudou a apresentar Paulo aos apóstolos.", dica_facil: "Companheiro missionário de Paulo.", referencia: "Atos 4:36", curiosidade: "Era levita, natural de Chipre." },
  { id: 48, nome: "TIMÓTEO", dica_dificil: "Foi aconselhado a não deixar desprezarem sua juventude.", dica_media: "Acompanhou Paulo em viagens.", dica_facil: "Recebeu cartas inspiradas.", referencia: "1 Timóteo 4:12", curiosidade: "Sua mãe era Eunice e avó Lóide." },
  { id: 49, nome: "LÍDIA", dica_dificil: "Era vendedora de púrpura de Tiatira.", dica_media: "Mostrou hospitalidade em Filipos.", dica_facil: "Uma das primeiras cristãs na Europa.", referencia: "Atos 16:14-15", curiosidade: "Seu coração foi aberto para a mensagem." },
  { id: 50, nome: "FEBE", dica_dificil: "Foi chamada servidora da congregação em Cencreia.", dica_media: "Foi recomendada por Paulo aos romanos.", dica_facil: "Cristã exemplar mencionada em Romanos.", referencia: "Romanos 16:1-2", curiosidade: "Apoiou muitos irmãos na obra cristã." }
];
